// Generated by https://quicktype.io

export interface Student {
    StudentID: string;
    FirstName: string;
    LastName:  string;
    Age:       number;
    Email:     string;
    Courses:   Course[];
}

export interface Course {
    CourseID:   string;
    CourseName: string;
    Grade:      string;
}
